### ISSUE TITLE
Change/Remove 'iti' token

### ISSUE THREAD

**Issue by washedszn** [Infotrend-Inc/CTPO#4]
Would like to be able to change or delete the `'iti'` token. Have looked at the Dockerfile to see how it's set and I'm not really sure how that can be changed within the unraid container page - tried adding `--IdentityProvider.token=''` to extra/post arguments, neither of which work.

**Comment by mmartial** [comment]
The steps you are taking are correct but you can not just add `--IdentityProvider.token=''`, you need to replace the entire `CMD` line.

When running manually from the command line, you would use:
```docker run --rm -it -v `pwd`:/iti -p 8888:8888 infotrend/ctpo-jupyter-tensorflow_pytorch_opencv:latest jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --IdentityProvider.token=''```
to get a direct access to the lab without being prompted by a page to enter the token.

Here you are redefining what the `CMD` line calls with `jupyter lab ...`

To do this on Unraid, edit the `Post Arguments` in the template and use the same content:
```jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --IdentityProvider.token=''```

Please let me know if this solve your issue.

**Comment by washedszn** [comment]
Perfect! Makes sense doing it that way, didn't think it was possible to override the existing jupyter lab session with a post argument command. I ended up removing the token paramter `jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root`, which means the token is generated (nice if you plan on forwarding jupyter lab outside your lan). Thanks for the help!
